# Generated by Django 5.0.1 on 2024-01-19 09:20

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=200)),
                ('cover_image', models.ImageField(upload_to='images/')),
                ('blog_description', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
