# Generated by Django 5.0.1 on 2024-01-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_blog_post_blog_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
