# Generated by Django 5.0.1 on 2024-02-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_blog_post_likes_blog_post_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='views',
        ),
        migrations.AddField(
            model_name='blog_post',
            name='like_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='view_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
